[package]
name = "solana-measure"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-measure"
readme = "../README.md"
version = "2.1.0"
edition = "2021"
rust-version = "1.88.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
